# Generated by Django 2.0 on 2018-01-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('coin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('coin_name', models.CharField(max_length=50)),
                ('github_link', models.TextField()),
                ('official_site_link', models.TextField()),
                ('total_contributors', models.IntegerField()),
                ('active_contributors', models.IntegerField()),
                ('read_me_score', models.IntegerField(default=0)),
                ('issues_score', models.IntegerField(default=0)),
                ('issues_open', models.IntegerField()),
                ('issues_closed', models.IntegerField()),
                ('pr_score', models.IntegerField(default=0)),
                ('pr_open', models.IntegerField()),
                ('pr_closed', models.IntegerField()),
                ('pr_merged', models.IntegerField()),
            ],
        ),
    ]
